import { WizardQuestion } from '@/types/assessment';

export const WIZARD_QUESTIONS: WizardQuestion[] = [
  {
    id: 'system_description',
    step: 1,
    question: 'What does your AI system do?',
    helpText: 'Describe the main purpose, inputs, and outputs of your AI system in plain language.',
    type: 'textarea',
    required: true,
  },
  {
    id: 'sector',
    step: 2,
    question: 'What sector does it operate in?',
    helpText: 'Select the primary sector where the AI system will be deployed.',
    type: 'select',
    options: [
      { label: 'Healthcare & Medical', value: 'healthcare' },
      { label: 'Employment & HR', value: 'employment' },
      { label: 'Education & Vocational Training', value: 'education' },
      { label: 'Credit & Finance', value: 'credit_finance' },
      { label: 'Law Enforcement', value: 'law_enforcement' },
      { label: 'Critical Infrastructure', value: 'critical_infrastructure' },
      { label: 'Migration & Border Control', value: 'migration' },
      { label: 'Administration of Justice', value: 'justice' },
      { label: 'General Enterprise / Internal Tools', value: 'enterprise' },
      { label: 'Other', value: 'other' },
    ],
    required: true,
    euAiActArticle: 'Annex III',
  },
  {
    id: 'end_users',
    step: 3,
    question: 'Who are the end users of this AI system?',
    helpText: 'Select all that apply.',
    type: 'select',
    options: [
      { label: 'General public', value: 'general_public' },
      { label: 'Employees / workers', value: 'employees' },
      { label: 'Regulated professionals (doctors, lawyers, etc.)', value: 'professionals' },
      { label: 'Automated systems (no human in loop)', value: 'automated' },
      { label: 'Vulnerable groups (minors, patients)', value: 'vulnerable' },
    ],
    required: true,
  },
  {
    id: 'affects_individuals',
    step: 4,
    question: 'Does it make or significantly influence decisions about individual people?',
    helpText: 'For example: hiring decisions, loan approvals, medical diagnoses, criminal risk scoring.',
    type: 'radio',
    options: [
      { label: 'Yes, it makes automated decisions', value: 'yes_automated' },
      { label: 'Yes, it influences human decisions', value: 'yes_influences' },
      { label: 'No', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 9',
  },
  {
    id: 'biometric_data',
    step: 5,
    question: 'Does it use facial recognition or biometric data?',
    helpText: 'This includes fingerprints, face scans, gait analysis, voice patterns, or emotion recognition.',
    type: 'radio',
    options: [
      { label: 'Yes, in real-time in public spaces', value: 'yes_realtime_public' },
      { label: 'Yes, but post-processing or private spaces only', value: 'yes_limited' },
      { label: 'No', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 5(1)(d)',
  },
  {
    id: 'scoring_profiling',
    step: 6,
    question: 'Does it score, rank, or profile people based on their behaviour or personal characteristics?',
    helpText: 'Includes social scoring, credit scoring, employee performance scoring, or risk profiling.',
    type: 'radio',
    options: [
      { label: 'Yes, for social/public benefit purposes by public authorities', value: 'yes_social' },
      { label: 'Yes, for private commercial purposes', value: 'yes_commercial' },
      { label: 'No', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 5(1)(c)',
  },
  {
    id: 'generative_ai',
    step: 7,
    question: 'Does it use generative AI or produce synthetic content?',
    helpText: 'Includes LLMs, image generators, deepfake tools, voice synthesis, or AI-generated text.',
    type: 'radio',
    options: [
      { label: 'Yes, it generates text', value: 'yes_text' },
      { label: 'Yes, it generates images/video/audio (deepfakes)', value: 'yes_media' },
      { label: 'Yes, it is a general-purpose chatbot/assistant', value: 'yes_chatbot' },
      { label: 'No', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 50',
  },
  {
    id: 'foundation_model',
    step: 8,
    question: 'Is it a foundation / general-purpose AI model trained on broad data?',
    helpText: 'Foundation models (e.g. GPT-4, Claude, Llama) have special GPAI obligations. If yes, provide estimated training FLOPs if known.',
    type: 'radio',
    options: [
      { label: 'Yes, training compute > 10²⁵ FLOPs (systemic risk threshold)', value: 'yes_systemic' },
      { label: 'Yes, but below 10²⁵ FLOPs threshold', value: 'yes_standard' },
      { label: 'No, it is a fine-tuned or task-specific model', value: 'no_finetuned' },
      { label: 'No, not a foundation model', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 51',
  },
  {
    id: 'training_data',
    step: 9,
    question: 'How was the training data collected and validated?',
    helpText: 'Describe data sources, consent mechanisms, bias checks, and GDPR compliance measures.',
    type: 'textarea',
    required: true,
    euAiActArticle: 'Article 10',
  },
  {
    id: 'human_oversight',
    step: 10,
    question: 'Are there human oversight mechanisms in place?',
    helpText: 'Can a human review, override, or stop the system? Is automation bias prevented?',
    type: 'radio',
    options: [
      { label: 'Yes — full human-in-the-loop with override capability', value: 'yes_full' },
      { label: 'Partial — humans are informed but cannot easily intervene', value: 'partial' },
      { label: 'No — fully automated with no human review', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 14',
  },
  {
    id: 'logging',
    step: 11,
    question: 'Does the system log decisions and events for audit purposes?',
    helpText: 'Automated logging enables traceability and post-market monitoring of serious incidents.',
    type: 'radio',
    options: [
      { label: 'Yes — full automated event logging with retention policy', value: 'yes' },
      { label: 'Partial — some logging but not comprehensive', value: 'partial' },
      { label: 'No', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 12',
  },
  {
    id: 'ai_disclosure',
    step: 12,
    question: 'Is the system\'s AI nature disclosed to end users?',
    helpText: 'Users interacting with chatbots, AI-generated content, or automated decision systems must be notified.',
    type: 'radio',
    options: [
      { label: 'Yes — users are clearly informed they interact with AI', value: 'yes' },
      { label: 'No — users are not informed', value: 'no' },
      { label: 'N/A — no direct user interaction', value: 'na' },
    ],
    required: true,
    euAiActArticle: 'Articles 13 & 50',
  },
  {
    id: 'impact_severity',
    step: 13,
    question: 'What are the consequences of a wrong or biased decision by this system?',
    helpText: 'Consider impacts on health, safety, fundamental rights, financial wellbeing, and reputation.',
    type: 'radio',
    options: [
      { label: 'Low — minor inconvenience, easily corrected', value: 'low' },
      { label: 'Medium — significant but reversible harm', value: 'medium' },
      { label: 'High — serious harm to rights, safety, or finances', value: 'high' },
      { label: 'Critical — irreversible harm, risk to life or fundamental rights', value: 'critical' },
    ],
    required: true,
  },
  {
    id: 'technical_documentation',
    step: 14,
    question: 'Do you have technical documentation for the system?',
    helpText: 'EU AI Act requires detailed technical documentation for high-risk systems (Annex IV).',
    type: 'radio',
    options: [
      { label: 'Yes — complete technical documentation exists', value: 'yes' },
      { label: 'In progress — partially documented', value: 'in_progress' },
      { label: 'No — no formal documentation yet', value: 'no' },
    ],
    required: true,
    euAiActArticle: 'Article 11 & Annex IV',
  },
  {
    id: 'deployment_status',
    step: 15,
    question: 'What is the current deployment status of the system?',
    helpText: 'This affects which EU AI Act obligations apply and when.',
    type: 'radio',
    options: [
      { label: 'Already deployed / in production', value: 'deployed' },
      { label: 'In testing / pilot phase', value: 'testing' },
      { label: 'Still in development', value: 'development' },
      { label: 'Planning stage only', value: 'planning' },
    ],
    required: true,
  },
];

export const TOTAL_STEPS = WIZARD_QUESTIONS.length;
